version: '3.1'

services:

  db:
    image: postgres:15.1
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    network_mode: host
#
#  mysql:
#    image: mysql:8.0.27
#    container_name: db-mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: mysql
#    ports:
#      - 3306:3306
#    network_mode: host
