import type { HttpMethod, RouteSchema, RouteSlot, TypeAlias } from './types';
import { camelCase, controllerKey, isValidIdentifier, quoteProp, splitPathSegments } from './normalize';

interface PathNode {
    methods: Map<HttpMethod, RouteSchema>;
    children: Map<string, PathNode>;
}

export function emitApp(routes: RouteSchema[], aliases: TypeAlias[] = []): string {
    const tree = buildTree(routes);
    const appType = emitNode(tree, 1);
    const pathConsts = emitPaths(routes);

    const lines = [
        '// Generated by @carno.js/client. Do not edit.',
        '// This file is overwritten automatically when the Carno app starts or the Vite/Bun plugin runs.',
        ''
    ];

    for (const alias of aliases) {
        lines.push(`export type ${alias.name} = ${alias.type};`);
    }

    if (aliases.length) {
        lines.push('');
    }

    lines.push(`export type App = ${appType};`);
    lines.push('');
    lines.push(pathConsts);
    lines.push('');

    return lines.join('\n');
}

function buildTree(routes: RouteSchema[]): PathNode {
    const root = emptyNode();

    for (const route of routes) {
        const segments = splitPathSegments(route.path);
        let node = root;

        for (const segment of segments) {
            const key = segment.startsWith(':') ? `:${segment.slice(1)}` : segment;
            if (!node.children.has(key)) {
                node.children.set(key, emptyNode());
            }
            node = node.children.get(key)!;
        }

        node.methods.set(route.method, route);
    }

    return root;
}

function emptyNode(): PathNode {
    return { methods: new Map(), children: new Map() };
}

function emitNode(node: PathNode, indent: number): string {
    const pad = '  '.repeat(indent);
    const close = '  '.repeat(indent - 1);
    const fields: string[] = [];

    const methodKeys = [...node.methods.keys()].sort();
    for (const method of methodKeys) {
        fields.push(`${pad}${method}: ${emitRouteType(node.methods.get(method)!)}`);
    }

    const childKeys = [...node.children.keys()].sort(compareSegments);
    for (const key of childKeys) {
        const child = node.children.get(key)!;
        fields.push(`${pad}${quoteProp(key)}: ${emitNode(child, indent + 1)}`);
    }

    if (!fields.length) {
        return 'Record<string, never>';
    }

    return `{\n${fields.join(';\n')};\n${close}}`;
}

function emitRouteType(route: RouteSchema): string {
    const parts: string[] = [];
    const params = namedSlotsObject(route.params);
    const query = slotsToType(route.query);
    const headers = slotsToType(route.headers);
    const body = slotsToType(route.body);

    if (params) {
        parts.push(`params: ${params}`);
    }
    if (query) {
        parts.push(`query: ${query}`);
    }
    if (headers) {
        parts.push(`headers: ${headers}`);
    }
    if (body) {
        parts.push(`body: ${body}`);
    }

    parts.push(`response: ${route.response}`);
    return `{ ${parts.join('; ')} }`;
}

function slotsToType(slots: RouteSlot[]): string | undefined {
    if (!slots.length) {
        return undefined;
    }

    const whole = slots.find((slot) => !slot.name);
    if (whole && slots.length === 1) {
        return whole.type;
    }

    if (whole && slots.length > 1) {
        const named = slots.filter((slot) => slot.name);
        const extras = namedSlotsObject(named);
        return extras ? `${whole.type} & ${extras}` : whole.type;
    }

    return namedSlotsObject(slots);
}

function namedSlotsObject(slots: RouteSlot[]): string | undefined {
    const named = slots.filter((slot) => slot.name);
    if (!named.length) {
        return undefined;
    }

    const fields = named.map((slot) => {
        const optional = slot.optional ? '?' : '';
        return `${quoteProp(slot.name!)}${optional}: ${slot.type}`;
    });

    return `{ ${fields.join('; ')} }`;
}

function emitPaths(routes: RouteSchema[]): string {
    const grouped = new Map<string, Map<string, string>>();

    for (const route of routes) {
        const group = pathGroup(route);
        if (!grouped.has(group)) {
            grouped.set(group, new Map());
        }

        const bucket = grouped.get(group)!;
        let key = route.handlerName;
        if (bucket.has(key) && bucket.get(key) !== route.path) {
            key = `${route.handlerName}_${route.method}`;
        }
        bucket.set(key, route.path);
    }

    const groups = [...grouped.keys()].sort();
    if (!groups.length) {
        return 'export const paths = {} as const;';
    }

    const lines = ['export const paths = {'];
    for (const group of groups) {
        const entries = [...grouped.get(group)!.entries()].sort(([a], [b]) => a.localeCompare(b));
        lines.push(`  ${quoteProp(group)}: {`);
        for (const [name, path] of entries) {
            lines.push(`    ${quoteProp(name)}: ${JSON.stringify(path)},`);
        }
        lines.push('  },');
    }
    lines.push('} as const;');
    return lines.join('\n');
}

function pathGroup(route: RouteSchema): string {
    const firstStatic = splitPathSegments(route.path).find((segment) => !segment.startsWith(':'));
    if (firstStatic) {
        return camelCase(firstStatic);
    }

    return camelCase(controllerKey(route.controllerName)) || 'routes';
}

function compareSegments(a: string, b: string): number {
    const aParam = a.startsWith(':') ? 1 : 0;
    const bParam = b.startsWith(':') ? 1 : 0;
    if (aParam !== bParam) {
        return aParam - bParam;
    }
    return a.localeCompare(b);
}

export function isHttpMethodName(value: string): value is HttpMethod {
    return value === 'get' || value === 'post' || value === 'put' || value === 'delete'
        || value === 'patch' || value === 'head' || value === 'options';
}

export function isIdentifierSegment(value: string): boolean {
    return isValidIdentifier(value);
}
